Fix compilation for builds without assertions enabled
This commit fixes builds that have assertions disabled(CONFIG_ASSERT=n) by
casting unused variables to void.

Before this fix a build that had assertions disabled would generate the following
errors:

/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c: In function 'cobs_encode_stream_single':
/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c:156:11: error: unused variable 'num_pulled' [-Werror=unused-variable]
  156 |    size_t num_pulled = net_buf_pull_across_fragments(&encode->buf, &zero, 1);
      |           ^~~~~~~~~~
/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c:232:10: error: unused variable 'num_pulled' [-Werror=unused-variable]
  232 |   size_t num_pulled = net_buf_pull_across_fragments(&encode->buf, output, 1);
      |          ^~~~~~~~~~
/home/spanceac/work/draeger-btplatform-connhub_modem/modules/lib/cobs/stream.c:264:10: error: unused variable 'num_pulled' [-Werror=unused-variable]
  264 |   size_t num_pulled = net_buf_pull_across_fragments(&encode->buf, output, 1);
      |          ^~~~~~~~~~

Signed-off-by: Sebastian Panceac <sebastian.panceac@ext.grandcentrix.net>