github: fetch with full depth
As soon as the given revision is not the latest one of one of the
branches anymore, `west update` stops working:

west.manifest: DEBUG: running 'git rev-parse '74981bf893e8b10931464b9945e2143d99a3f0a3^{commit}'' in /var/home/m1cha/nbu/cobstest/modules/hal/cmsis
west.manifest: DEBUG: "git rev-parse '74981bf893e8b10931464b9945e2143d99a3f0a3^{commit}'" exit code: 128 stdout: b'74981bf893e8b10931464b9945e2143d99a3f0a3^{commit}\n' stderr: b"fatal: ambiguous argument '74981bf893e8b10931464b9945e2143d99a3f0a3^{commit}': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n"
ERROR: update failed for project cmsis

I don't have a solution for this right now and I don't want to invest
the time to solve this given that the time difference isn't that big for
COBS due to the west-ci.yml only allowing cmsis. COBS also isn't a
project with lots of PR activity where a change like this would waste
everyones time.